import { FileDown } from "lucide-react";
import { useState } from "react";

import { downloadModelReport } from "../services/api.js";

const reportDownloadKeys = {
  "Confusion Matrix": "confusionMatrix",
  "ROC Curve": "rocCurve",
  "Precision-Recall Curve": "precisionRecallCurve",
  "Feature Importance": "featureImportance",
  "Metrics JSON": "metricsJson",
};

export default function ModelReportsCard({ reports }) {
  const [downloadingReport, setDownloadingReport] = useState("");
  const [message, setMessage] = useState("");
  const [messageTone, setMessageTone] = useState("info");

  async function handleDownload(report) {
    const reportKey = reportDownloadKeys[report];
    if (!reportKey) {
      setMessage("Report download is not configured.");
      setMessageTone("error");
      return;
    }

    try {
      setDownloadingReport(report);
      setMessage("");
      await downloadModelReport(reportKey);
      setMessage(`${report} download started.`);
      setMessageTone("success");
    } catch (error) {
      setMessage(error.message);
      setMessageTone("error");
    } finally {
      setDownloadingReport("");
    }
  }

  return (
    <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="mb-6">
        <h2 className="text-lg font-semibold text-slate-950">
          Generated Model Reports
        </h2>
        <p className="mt-1 text-sm text-slate-500">
          Evaluation artifacts prepared for model review.
        </p>
      </div>

      <div className="space-y-3">
        {reports.map((report) => (
          <div
            key={report}
            className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"
          >
            <div className="flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700">
                <FileDown className="h-5 w-5" aria-hidden="true" />
              </span>
              <span className="text-sm font-semibold text-slate-800">{report}</span>
            </div>
            <button
              type="button"
              disabled={downloadingReport === report}
              className="inline-flex min-h-9 items-center justify-center rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 transition hover:border-blue-200 hover:text-blue-700 disabled:cursor-not-allowed disabled:text-slate-400"
              onClick={() => handleDownload(report)}
            >
              {downloadingReport === report ? "Downloading" : "Download"}
            </button>
          </div>
        ))}
      </div>

      {message ? (
        <p
          className={`mt-5 rounded-xl px-4 py-3 text-sm font-medium ${
            messageTone === "error"
              ? "bg-rose-50 text-rose-700"
              : "bg-emerald-50 text-emerald-700"
          }`}
        >
          {message}
        </p>
      ) : (
        <p className="mt-5 rounded-xl bg-violet-50 px-4 py-3 text-sm font-medium text-violet-700">
          Downloads use the latest files generated by the ML pipeline.
        </p>
      )}
    </article>
  );
}
